import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import { Nav, NavbarBrand, Form, Button } from "react-bootstrap";
import { useState } from "react";

import { GetStaticProps } from "next";
import { serverTexts } from "@/lib/texts_utils";
import { useTexts } from "@/lib/hooks";
import NavBar from "@/components/NavBar";

export default function Home() {
    const { t } = useTexts();

    return (
        <div className="m-100">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar t={t} />
            <h1>404</h1>
        </div>
    );
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
    const translations = await serverTexts(locale);
    return {
        props: {
            ...translations,
        },
    };
};
